SLURM_SUBMIT_DIR=/home/gungun625/CSED490F_DDP_DALI_Training
CUDA_HOME=/opt/ohpc/pub/apps/cuda-11.2
CUDA_VISIBLE_DEVICES=0,1
CUDA_VERSION=11.2
0: n6
0: /home/gungun625/CSED490F_DDP_DALI_Training
0: Wed Oct  1 23:04:40 KST 2025
gungun625_CSED490F_DDP_DALI_Training_container
week4: Pulling from 25fallcsed490f/cluster
Digest: sha256:26ce44420c5de1cce8fe2e192bcf0329e6708d6dddb23d229bc2d0ab55802b97
Status: Image is up to date for 25fallcsed490f/cluster:week4
docker.io/25fallcsed490f/cluster:week4
[System] UUID GPU List
[System] create docker container...
f3ab8fca8577863665b3e3b8dbc09d242c2f2795053434b29f9e4dfa80bded96
[System] docker container created
[System] initialize docker container...
Requirement already satisfied: numpy<2 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: nvidia-dali-cuda120 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (1.51.2)
Requirement already satisfied: pynvml in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (13.0.1)
Requirement already satisfied: pandas in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (2.3.2)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (3.10.6)
Requirement already satisfied: nvtx in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 6)) (0.2.13)
Requirement already satisfied: astunparse<=1.6.3,>=1.6.0 in /opt/conda/lib/python3.11/site-packages (from nvidia-dali-cuda120->-r requirements.txt (line 2)) (1.6.3)
Requirement already satisfied: gast<=0.6.0,>=0.3.3 in /opt/conda/lib/python3.11/site-packages (from nvidia-dali-cuda120->-r requirements.txt (line 2)) (0.6.0)
Requirement already satisfied: six<=1.17,>=1.16 in /opt/conda/lib/python3.11/site-packages (from nvidia-dali-cuda120->-r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: packaging<=25.0 in /opt/conda/lib/python3.11/site-packages (from nvidia-dali-cuda120->-r requirements.txt (line 2)) (24.1)
Requirement already satisfied: nvidia-nvimgcodec-cu12<0.7.0,>=0.6.0 in /opt/conda/lib/python3.11/site-packages (from nvidia-nvimgcodec-cu12[all]<0.7.0,>=0.6.0->nvidia-dali-cuda120->-r requirements.txt (line 2)) (0.6.0.32)
Requirement already satisfied: nvidia-nvcomp-cu12==5.0.0.6 in /opt/conda/lib/python3.11/site-packages (from nvidia-dali-cuda120->-r requirements.txt (line 2)) (5.0.0.6)
Requirement already satisfied: dm-tree<=0.1.9 in /opt/conda/lib/python3.11/site-packages (from nvidia-dali-cuda120->-r requirements.txt (line 2)) (0.1.9)
Requirement already satisfied: nvidia-ml-py>=12.0.0 in /opt/conda/lib/python3.11/site-packages (from pynvml->-r requirements.txt (line 3)) (13.580.82)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas->-r requirements.txt (line 4)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas->-r requirements.txt (line 4)) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.11/site-packages (from pandas->-r requirements.txt (line 4)) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib->-r requirements.txt (line 5)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.11/site-packages (from matplotlib->-r requirements.txt (line 5)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.11/site-packages (from matplotlib->-r requirements.txt (line 5)) (4.60.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib->-r requirements.txt (line 5)) (1.4.9)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.11/site-packages (from matplotlib->-r requirements.txt (line 5)) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib->-r requirements.txt (line 5)) (3.2.5)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /opt/conda/lib/python3.11/site-packages (from astunparse<=1.6.3,>=1.6.0->nvidia-dali-cuda120->-r requirements.txt (line 2)) (0.44.0)
Requirement already satisfied: absl-py>=0.6.1 in /opt/conda/lib/python3.11/site-packages (from dm-tree<=0.1.9->nvidia-dali-cuda120->-r requirements.txt (line 2)) (2.3.1)
Requirement already satisfied: attrs>=18.2.0 in /opt/conda/lib/python3.11/site-packages (from dm-tree<=0.1.9->nvidia-dali-cuda120->-r requirements.txt (line 2)) (24.2.0)
Requirement already satisfied: wrapt>=1.11.2 in /opt/conda/lib/python3.11/site-packages (from dm-tree<=0.1.9->nvidia-dali-cuda120->-r requirements.txt (line 2)) (1.17.3)
Requirement already satisfied: nvidia-nvjpeg-cu12 in /opt/conda/lib/python3.11/site-packages (from nvidia-nvimgcodec-cu12[all]<0.7.0,>=0.6.0->nvidia-dali-cuda120->-r requirements.txt (line 2)) (12.4.0.76)
Requirement already satisfied: nvidia-nvjpeg2k-cu12 in /opt/conda/lib/python3.11/site-packages (from nvidia-nvimgcodec-cu12[all]<0.7.0,>=0.6.0->nvidia-dali-cuda120->-r requirements.txt (line 2)) (0.9.0.43)
Requirement already satisfied: nvidia-nvtiff-cu12 in /opt/conda/lib/python3.11/site-packages (from nvidia-nvimgcodec-cu12[all]<0.7.0,>=0.6.0->nvidia-dali-cuda120->-r requirements.txt (line 2)) (0.5.1.75)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
[System] initialize docker container finished
[System] run train_cifar.py with 'run_dp.sh'...
scripts/launch.sh: line 2: $'\r': command not found
scripts/launch.sh: line 3: export: `DATA_DIR': not a valid identifier
scripts/launch.sh: line 4: export: `CKPT_DIR': not a valid identifier
scripts/launch.sh: line 5: export: `NSIGHT_LOG_DIR': not a valid identifier
scripts/launch.sh: line 6: export: `NSIGHT_FILE_NAME': not a valid identifier
scripts/launch.sh: line 7: export: `MODE': not a valid identifier
scripts/launch.sh: line 8: export: `LOCAL_GPU_IDS': not a valid identifier
scripts/launch.sh: line 9: export: `NUM_GPUS': not a valid identifier
scripts/launch.sh: line 10: $'\r': command not found
scripts/launch.sh: line 15: $'\r': command not found
scripts/launch.sh: line 16: $'\r': command not found
scripts/launch.sh: line 18: $'\r': command not found
WARNING: CPU IP/backtrace sampling not supported, disabling.
Try the 'nsys status --environment' command to learn more.

WARNING: CPU context switch tracing not supported, disabling.
Try the 'nsys status --environment' command to learn more.

Executable '' not found in current directory or standard search paths
scripts/launch.sh: line 20: --force-overwrite=true: command not found
scripts/launch.sh: line 21: --output: command not found
scripts/launch.sh: line 22: --trace=cuda,cublas,cudnn,nvtx,osrt: command not found
/opt/conda/lib/python3.11/site-packages/torch/cuda/__init__.py:58: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
usage: train_cifar.py [-h] --num_gpu NUM_GPU [--ip IP] [--port PORT]
                      [--data DATA] --ckpt CKPT [--save_ckpt] [--lr LR]
                      [--decay DECAY] [--seed SEED] [--mode {dp,ddp,ddp_dali}]
train_cifar.py: error: the following arguments are required: --num_gpu, --ckpt
scripts/launch.sh: line 24: --num_gpu=1: command not found
scripts/launch.sh: line 25: --data=/DATA/cifar10: No such file or directory
scripts/launch.sh: line 26: --ckpt=runs/dp_20251001_140444/gpu_1: No such file or directory
scripts/launch.sh: line 27: --mode=dp: command not found
scripts/launch.sh: line 28: $'--save_ckpt1\r': command not found
scripts/launch.sh: line 2: $'\r': command not found
scripts/launch.sh: line 3: export: `DATA_DIR': not a valid identifier
scripts/launch.sh: line 4: export: `CKPT_DIR': not a valid identifier
scripts/launch.sh: line 5: export: `NSIGHT_LOG_DIR': not a valid identifier
scripts/launch.sh: line 6: export: `NSIGHT_FILE_NAME': not a valid identifier
scripts/launch.sh: line 7: export: `MODE': not a valid identifier
scripts/launch.sh: line 8: export: `LOCAL_GPU_IDS': not a valid identifier
scripts/launch.sh: line 9: export: `NUM_GPUS': not a valid identifier
scripts/launch.sh: line 10: $'\r': command not found
scripts/launch.sh: line 15: $'\r': command not found
scripts/launch.sh: line 16: $'\r': command not found
scripts/launch.sh: line 18: $'\r': command not found
WARNING: CPU IP/backtrace sampling not supported, disabling.
Try the 'nsys status --environment' command to learn more.

WARNING: CPU context switch tracing not supported, disabling.
Try the 'nsys status --environment' command to learn more.

Executable '' not found in current directory or standard search paths
scripts/launch.sh: line 20: --force-overwrite=true: command not found
scripts/launch.sh: line 21: --output: command not found
scripts/launch.sh: line 22: --trace=cuda,cublas,cudnn,nvtx,osrt: command not found
/opt/conda/lib/python3.11/site-packages/torch/cuda/__init__.py:58: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
usage: train_cifar.py [-h] --num_gpu NUM_GPU [--ip IP] [--port PORT]
                      [--data DATA] --ckpt CKPT [--save_ckpt] [--lr LR]
                      [--decay DECAY] [--seed SEED] [--mode {dp,ddp,ddp_dali}]
train_cifar.py: error: the following arguments are required: --num_gpu, --ckpt
scripts/launch.sh: line 24: --num_gpu=2: command not found
scripts/launch.sh: line 25: --data=/DATA/cifar10: No such file or directory
scripts/launch.sh: line 26: --ckpt=runs/dp_20251001_140444/gpu_2: No such file or directory
scripts/launch.sh: line 27: --mode=dp: command not found
scripts/launch.sh: line 28: $'--save_ckpt1\r': command not found
[System] train ended
gungun625_CSED490F_DDP_DALI_Training_container
gungun625_CSED490F_DDP_DALI_Training_container
Wed Oct  1 23:04:59 KST 2025
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
             36029   titanxp CSED490F gungun62  R       0:20      1 n6
##### END #####
[System] change permission in docker container created files
Error response from daemon: No such container: gungun625_CSED490F_DDP_DALI_Training_container
Error response from daemon: No such container: gungun625_CSED490F_DDP_DALI_Training_container
[System] docker container stopped
Error response from daemon: No such container: gungun625_CSED490F_DDP_DALI_Training_container
[System] docker container removed
